// This file is @generated by prost-build.
/// Request/Response messages
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockNumberRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockNumberResponse {
    /// Hex string
    #[prost(string, tag = "1")]
    pub block_number: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockByNumberRequest {
    /// Hex string or "latest"
    #[prost(string, tag = "1")]
    pub block_number: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub include_transactions: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockByNumberResponse {
    #[prost(message, optional, tag = "1")]
    pub block: ::core::option::Option<Block>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockByHashRequest {
    /// Hex string
    #[prost(string, tag = "1")]
    pub hash: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub include_transactions: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockByHashResponse {
    #[prost(message, optional, tag = "1")]
    pub block: ::core::option::Option<Block>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBalanceRequest {
    /// Hex string
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Hex string or "latest"
    #[prost(string, tag = "2")]
    pub block_number: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBalanceResponse {
    /// Hex string
    #[prost(string, tag = "1")]
    pub balance: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTransactionCountRequest {
    /// Hex string
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Hex string or "latest"
    #[prost(string, tag = "2")]
    pub block_number: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTransactionCountResponse {
    /// Hex string (nonce)
    #[prost(string, tag = "1")]
    pub count: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendRawTransactionRequest {
    /// Hex string
    #[prost(string, tag = "1")]
    pub raw_transaction: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendRawTransactionResponse {
    /// Hex string
    #[prost(string, tag = "1")]
    pub transaction_hash: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTransactionByHashRequest {
    /// Hex string
    #[prost(string, tag = "1")]
    pub hash: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTransactionByHashResponse {
    #[prost(message, optional, tag = "1")]
    pub transaction: ::core::option::Option<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTransactionReceiptRequest {
    /// Hex string
    #[prost(string, tag = "1")]
    pub hash: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTransactionReceiptResponse {
    #[prost(message, optional, tag = "1")]
    pub receipt: ::core::option::Option<TransactionReceipt>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDagStatsRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDagStatsResponse {
    #[prost(uint64, tag = "1")]
    pub total_blocks: u64,
    #[prost(uint64, tag = "2")]
    pub blue_blocks: u64,
    #[prost(uint64, tag = "3")]
    pub red_blocks: u64,
    #[prost(uint64, tag = "4")]
    pub total_transactions: u64,
    #[prost(uint64, tag = "5")]
    pub total_size_bytes: u64,
    #[prost(uint64, tag = "6")]
    pub avg_block_size: u64,
    #[prost(uint64, tag = "7")]
    pub avg_txs_per_block: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPeerCountRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPeerCountResponse {
    #[prost(uint32, tag = "1")]
    pub peer_count: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGasPriceRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGasPriceResponse {
    /// Hex string
    #[prost(string, tag = "1")]
    pub gas_price: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallRequest {
    #[prost(message, optional, tag = "1")]
    pub call: ::core::option::Option<TransactionCall>,
    /// Hex string or "latest"
    #[prost(string, tag = "2")]
    pub block_number: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallResponse {
    /// Hex string (return data)
    #[prost(string, tag = "1")]
    pub result: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EstimateGasRequest {
    #[prost(message, optional, tag = "1")]
    pub call: ::core::option::Option<TransactionCall>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EstimateGasResponse {
    /// Hex string
    #[prost(string, tag = "1")]
    pub gas_estimate: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCodeRequest {
    /// Hex string
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Hex string or "latest"
    #[prost(string, tag = "2")]
    pub block_number: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCodeResponse {
    /// Hex string
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
}
/// Data structures
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(string, tag = "1")]
    pub hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub parent_hash: ::prost::alloc::string::String,
    /// For DAG
    #[prost(string, repeated, tag = "3")]
    pub parent_hashes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, tag = "4")]
    pub block_number: u64,
    #[prost(uint64, tag = "5")]
    pub timestamp: u64,
    #[prost(uint64, tag = "6")]
    pub difficulty: u64,
    /// Hex string
    #[prost(string, tag = "7")]
    pub nonce: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub transactions_root: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "9")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    /// 0=A, 1=B, 2=C
    #[prost(uint32, tag = "10")]
    pub stream_type: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(string, tag = "1")]
    pub hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub to: ::prost::alloc::string::String,
    /// Hex string
    #[prost(string, tag = "4")]
    pub value: ::prost::alloc::string::String,
    /// Hex string
    #[prost(string, tag = "5")]
    pub data: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub nonce: u64,
    /// Hex string
    #[prost(string, tag = "7")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag = "8")]
    pub gas_limit: u64,
    #[prost(uint32, tag = "9")]
    pub v: u32,
    /// Hex string
    #[prost(string, tag = "10")]
    pub r: ::prost::alloc::string::String,
    /// Hex string
    #[prost(string, tag = "11")]
    pub s: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionReceipt {
    #[prost(string, tag = "1")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub block_number: u64,
    #[prost(string, tag = "3")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub transaction_index: u64,
    #[prost(string, tag = "5")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub to: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub gas_used: u64,
    #[prost(uint64, tag = "8")]
    pub cumulative_gas_used: u64,
    /// Empty if not a contract creation
    #[prost(string, tag = "9")]
    pub contract_address: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
    /// "0x1" for success, "0x0" for failure
    #[prost(string, tag = "11")]
    pub status: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Hex strings
    #[prost(string, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Hex string
    #[prost(string, tag = "3")]
    pub data: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub block_number: u64,
    #[prost(string, tag = "5")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub transaction_index: u64,
    #[prost(uint64, tag = "8")]
    pub log_index: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionCall {
    /// Hex string (optional)
    #[prost(string, tag = "1")]
    pub from: ::prost::alloc::string::String,
    /// Hex string
    #[prost(string, tag = "2")]
    pub to: ::prost::alloc::string::String,
    /// Hex string (optional)
    #[prost(string, tag = "3")]
    pub value: ::prost::alloc::string::String,
    /// Hex string (optional)
    #[prost(string, tag = "4")]
    pub data: ::prost::alloc::string::String,
    /// Hex string (optional)
    #[prost(string, tag = "5")]
    pub gas_price: ::prost::alloc::string::String,
    /// Optional
    #[prost(uint64, tag = "6")]
    pub gas_limit: u64,
}
