//! QUIC Transport Module for P2P Communication
//!
//! Provides QUIC-based transport with TLS 1.3 for encrypted P2P connections.
//! Uses self-signed certificates with Ed25519 node identity embedded for peer verification.
//!
//! Copyright (c) 2024-2026 IronDAG Project
//! Licensed under the Business Source License 1.1

use std::net::SocketAddr;
use std::sync::{Arc, OnceLock};
use std::time::Duration;

use quinn::{ClientConfig, Endpoint, ServerConfig};
use rustls::pki_types::{CertificateDer, PrivateKeyDer, ServerName, UnixTime};

/// Initialize the rustls crypto provider once
/// This must be called before any QUIC operations
pub fn init_crypto_provider() {
    // Only install if not already installed
    if rustls::crypto::ring::default_provider()
        .install_default()
        .is_ok()
    {
        tracing::debug!("Installed ring crypto provider for rustls");
    }
}

/// Cached QUIC client config for reuse across all outgoing connections.
/// This config uses the InsecureCertVerifier since identity verification
/// is performed at the application layer via extract_peer_identity().
static QUIC_CLIENT_CONFIG: OnceLock<quinn::ClientConfig> = OnceLock::new();

/// Get or initialize the cached QUIC client config.
/// The config is safe to cache because it doesn't depend on per-connection state -
/// all identity verification happens at the application layer.
fn get_or_init_client_config() -> quinn::ClientConfig {
    QUIC_CLIENT_CONFIG
        .get_or_init(|| {
            let mut client_config = rustls::ClientConfig::builder()
                .dangerous()
                .with_custom_certificate_verifier(Arc::new(InsecureCertVerifier))
                .with_no_client_auth();
            client_config.alpn_protocols = vec![b"irondag/1".to_vec()];

            ClientConfig::new(Arc::new(
                quinn::crypto::rustls::QuicClientConfig::try_from(client_config)
                    .expect("Failed to create QUIC client config"),
            ))
        })
        .clone()
}

/// Stream type identifier for gossip protocol messages
pub const STREAM_TYPE_GOSSIP: u8 = 0x01;
/// Stream type identifier for blockchain sync messages
pub const STREAM_TYPE_SYNC: u8 = 0x02;
/// Stream type identifier for Kyber key exchange
pub const STREAM_TYPE_KYBER: u8 = 0x03;

/// QUIC transport wrapper containing the endpoint
pub struct QuicTransport {
    /// The QUIC endpoint for sending and receiving connections
    pub endpoint: Endpoint,
}

/// Custom TLS certificate verifier for P2P networks with self-signed certificates.
///
/// This verifier implements a trust model appropriate for decentralized P2P networks:
/// - Accepts self-signed certificates (required for ephemeral node identities)
/// - Checks certificate validity period (rejects expired/not-yet-valid certs)
/// - Validates basic certificate structure
///
/// Identity verification (checking the Ed25519 public key in SAN) is performed
/// at the application layer via `extract_peer_identity()`. This is the correct
/// security model for P2P networks where nodes generate their own ephemeral certs
/// and trust is established through known peer identities, not CAs.
#[derive(Debug)]
struct InsecureCertVerifier;

impl rustls::client::danger::ServerCertVerifier for InsecureCertVerifier {
    fn verify_server_cert(
        &self,
        end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _server_name: &ServerName<'_>,
        _ocsp_response: &[u8],
        now: UnixTime,
    ) -> Result<rustls::client::danger::ServerCertVerified, rustls::Error> {
        // Parse the certificate to verify structure and validity
        let cert_der = end_entity.as_ref();

        let (_, cert) = x509_parser::parse_x509_certificate(cert_der)
            .map_err(|e| rustls::Error::General(format!("Failed to parse certificate: {}", e)))?;

        // Check certificate validity period
        // x509_parser's ASN1Time stores timestamp as Unix timestamp
        let now_secs = now.as_secs() as i64;
        let validity = &cert.tbs_certificate.validity;

        // Get timestamps for comparison
        let not_before_ts = validity.not_before.timestamp();
        let not_after_ts = validity.not_after.timestamp();

        // Check not_before
        if now_secs < not_before_ts {
            return Err(rustls::Error::General(
                "Certificate not yet valid".to_string(),
            ));
        }

        // Check not_after
        if now_secs > not_after_ts {
            return Err(rustls::Error::General(
                "Certificate has expired".to_string(),
            ));
        }

        // Note: We intentionally do NOT verify the certificate's self-signature here.
        // For P2P networks with ephemeral self-signed certificates:
        // - The TLS certificate is generated by each node using rcgen
        // - The certificate's role is to encrypt the QUIC connection
        // - Identity is verified at the application layer via extract_peer_identity()
        //   which extracts the Ed25519 public key from the SAN extension
        // - Rejecting based on signature verification would break the P2P model
        //   since self-signed certs aren't signed by a trusted CA
        //
        // The security model is: "I trust this peer's Ed25519 key" (known peers list)
        // NOT "I trust this certificate's issuer" (CA model)

        Ok(rustls::client::danger::ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        // Use the default crypto provider (ring) to verify the signature
        rustls::crypto::verify_tls12_signature(
            message,
            cert,
            dss,
            &rustls::crypto::ring::default_provider().signature_verification_algorithms,
        )
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        // Use the default crypto provider (ring) to verify the signature
        rustls::crypto::verify_tls13_signature(
            message,
            cert,
            dss,
            &rustls::crypto::ring::default_provider().signature_verification_algorithms,
        )
    }

    fn supported_verify_schemes(&self) -> Vec<rustls::SignatureScheme> {
        vec![
            rustls::SignatureScheme::ECDSA_NISTP256_SHA256,
            rustls::SignatureScheme::ECDSA_NISTP384_SHA384,
            rustls::SignatureScheme::ED25519,
            rustls::SignatureScheme::RSA_PKCS1_SHA256,
            rustls::SignatureScheme::RSA_PKCS1_SHA384,
            rustls::SignatureScheme::RSA_PKCS1_SHA512,
        ]
    }
}

/// Generate a self-signed TLS certificate with the node's Ed25519 public key embedded
///
/// The certificate includes the node's Ed25519 public key in the Subject Alternative Name
/// extension, allowing peers to extract and verify the node identity.
fn generate_self_signed_cert(
    node_signing_key: &ed25519_dalek::SigningKey,
) -> Result<(Vec<CertificateDer<'static>>, PrivateKeyDer<'static>), Box<dyn std::error::Error>> {
    // Generate ECDSA P-256 key pair for TLS
    let key_pair = rcgen::KeyPair::generate()?;

    // Create certificate parameters
    let mut params = rcgen::CertificateParams::new(vec!["irondag.local".to_string()])?;

    // Set the certificate to be self-signed and valid for 1 year
    params.not_before = time::OffsetDateTime::now_utc();
    params.not_after = time::OffsetDateTime::now_utc() + time::Duration::days(365);

    // Embed the Ed25519 public key as a URI in the Subject Alternative Name
    // Using URI SAN type is valid per RFC 5280, unlike the previous invalid DNS name approach
    let verifying_key = node_signing_key.verifying_key();
    let public_key_bytes = verifying_key.as_bytes();
    let san_value = format!("irondag:{}", hex::encode(public_key_bytes));
    let ia5_string = rcgen::Ia5String::try_from(san_value)?;
    params.subject_alt_names = vec![rcgen::SanType::URI(ia5_string)];

    // Self-sign the certificate
    let cert = params.self_signed(&key_pair)?;
    let cert_der = cert.der().clone();
    let key_der = key_pair.serialize_der();

    let cert_chain = vec![cert_der];
    let key = PrivateKeyDer::try_from(key_der).map_err(|_| "Invalid private key")?;

    Ok((cert_chain, key))
}

/// Create a QUIC endpoint configured for P2P communication
///
/// # Arguments
/// * `listen_addr` - The socket address to bind the endpoint to
/// * `node_signing_key` - The node's Ed25519 signing key for identity
/// * `idle_timeout_secs` - QUIC connection idle timeout in seconds (default: 30)
///
/// # Returns
/// A configured `quinn::Endpoint` ready for accepting and initiating connections
///
/// # Errors
/// Returns an error if certificate generation fails or the endpoint cannot be created
pub fn create_endpoint(
    listen_addr: SocketAddr,
    node_signing_key: &ed25519_dalek::SigningKey,
    idle_timeout_secs: u64,
) -> Result<Endpoint, Box<dyn std::error::Error>> {
    // Generate self-signed certificate with node identity
    let (cert_chain, key) = generate_self_signed_cert(node_signing_key)?;

    // Create server TLS config
    let mut server_config = rustls::ServerConfig::builder()
        .with_no_client_auth()
        .with_single_cert(cert_chain.clone(), key)?;

    // Configure ALPN protocols for QUIC (must match on both sides)
    server_config.alpn_protocols = vec![b"irondag/1".to_vec()];

    // Create client TLS config with custom verifier
    let mut client_config = rustls::ClientConfig::builder()
        .dangerous()
        .with_custom_certificate_verifier(Arc::new(InsecureCertVerifier))
        .with_no_client_auth();

    // Configure ALPN protocols for QUIC (must match on both sides)
    client_config.alpn_protocols = vec![b"irondag/1".to_vec()];

    // Create QUIC server config
    let mut quinn_server_config = ServerConfig::with_crypto(Arc::new(
        quinn::crypto::rustls::QuicServerConfig::try_from(server_config)?,
    ));

    // Configure transport parameters
    let mut transport_config = quinn::TransportConfig::default();
    transport_config.max_idle_timeout(Some(Duration::from_secs(idle_timeout_secs).try_into()?));
    transport_config.keep_alive_interval(Some(Duration::from_secs(10)));
    quinn_server_config.transport_config(Arc::new(transport_config));

    // Create a UDP socket with SO_REUSEADDR to allow rapid restart on the same port
    // This is important for tests that restart nodes on the same port
    let socket = create_reuse_addr_socket(listen_addr)?;

    // Get the default async runtime
    let runtime = quinn::default_runtime()
        .ok_or("No async runtime found. Ensure this is called from within a Tokio runtime.")?;

    // Create endpoint with server capabilities using the pre-bound socket
    let endpoint = Endpoint::new(
        quinn::EndpointConfig::default(),
        Some(quinn_server_config),
        socket,
        runtime,
    )
    .map_err(|e| format!("Failed to create QUIC endpoint: {}", e))?;

    // Note: In quinn 0.11, we set default client config separately
    // The endpoint is created with server config, and client config is used per-connection

    Ok(endpoint)
}

/// Create a UDP socket with SO_REUSEADDR option set to allow rapid port reuse.
///
/// This is essential for integration tests that restart nodes on the same port,
/// as it prevents "Address already in use" errors during the TIME_WAIT period.
///
/// # Arguments
/// * `listen_addr` - The socket address to bind the socket to
///
/// # Returns
/// A configured `std::net::UdpSocket` with SO_REUSEADDR set
fn create_reuse_addr_socket(
    listen_addr: SocketAddr,
) -> Result<std::net::UdpSocket, Box<dyn std::error::Error>> {
    use socket2::{Domain, Socket, Type};

    let domain = if listen_addr.is_ipv4() {
        Domain::IPV4
    } else {
        Domain::IPV6
    };

    let socket = Socket::new(domain, Type::DGRAM, None)?;

    // Set SO_REUSEADDR to allow rapid restart on the same port
    socket.set_reuse_address(true)?;

    // On Unix systems, also set SO_REUSEPORT for better load distribution
    // (this is a no-op on Windows)
    #[cfg(unix)]
    {
        socket.set_reuse_port(true)?;
    }

    // Bind the socket to the address
    socket.bind(&listen_addr.into())?;

    // Convert to std::net::UdpSocket
    Ok(socket.into())
}

/// Accept an incoming QUIC connection
///
/// # Arguments
/// * `endpoint` - The QUIC endpoint to accept connections on
///
/// # Returns
/// An established `quinn::Connection` if a connection is accepted, or `None` if the endpoint is closed
pub async fn accept_connection(endpoint: &Endpoint) -> Option<quinn::Connection> {
    match endpoint.accept().await {
        Some(incoming) => match incoming.await {
            Ok(connection) => Some(connection),
            Err(e) => {
                tracing::warn!("Failed to accept incoming connection: {}", e);
                None
            }
        },
        None => {
            // Endpoint closed
            None
        }
    }
}

/// Connect to a peer at the specified address
///
/// # Arguments
/// * `endpoint` - The QUIC endpoint to use for the connection
/// * `addr` - The socket address of the peer to connect to
///
/// # Returns
/// An established `quinn::Connection` on success
///
/// # Errors
/// Returns a `quinn::ConnectionError` if the connection fails
pub async fn connect_to_peer(
    endpoint: &Endpoint,
    addr: SocketAddr,
) -> Result<quinn::Connection, Box<dyn std::error::Error + Send + Sync>> {
    // Use the cached client config
    let quinn_client_config = get_or_init_client_config();

    let connection = endpoint
        .connect_with(quinn_client_config, addr, "irondag")?
        .await?;

    Ok(connection)
}

/// Extract the peer's identity (Ed25519 public key) from a QUIC connection
///
/// # Arguments
/// * `connection` - The established QUIC connection
///
/// # Returns
/// The raw public key bytes if the identity can be extracted, or `None` if extraction fails
pub fn extract_peer_identity(connection: &quinn::Connection) -> Option<Vec<u8>> {
    // Get the peer's certificate from the connection
    let peer_identity = connection.peer_identity()?;

    // Downcast to the certificate chain type
    let certs: &Vec<rustls::pki_types::CertificateDer<'_>> =
        peer_identity.downcast_ref::<Vec<rustls::pki_types::CertificateDer<'_>>>()?;

    if certs.is_empty() {
        return None;
    }

    // Parse the first certificate to extract the public key from SAN
    let cert_der = &certs[0];

    // Parse the certificate using x509-parser
    match x509_parser::parse_x509_certificate(cert_der.as_ref()) {
        Ok((_, cert)) => {
            // Look for Subject Alternative Names
            for ext in cert.extensions() {
                if ext.oid == x509_parser::oid_registry::OID_X509_EXT_SUBJECT_ALT_NAME {
                    let san = ext.parsed_extension();
                    if let x509_parser::extensions::ParsedExtension::SubjectAlternativeName(san) =
                        san
                    {
                        for name in san.general_names.iter() {
                            // Preferred: URI SAN (new format, valid per RFC 5280)
                            if let x509_parser::extensions::GeneralName::URI(uri) = name {
                                let uri_str = uri.to_string();
                                if uri_str.starts_with("irondag:") {
                                    // Extract the hex-encoded public key
                                    let hex_key = &uri_str[12..]; // Skip "irondag:"
                                    if let Ok(key_bytes) = hex::decode(hex_key) {
                                        return Some(key_bytes);
                                    }
                                }
                            }

                            // Backward compatibility: legacy DNS SAN format
                            if let x509_parser::extensions::GeneralName::DNSName(dns) = name {
                                let dns_str = dns.to_string();
                                if dns_str.starts_with("irondag:") {
                                    // Extract the hex-encoded public key
                                    let hex_key = &dns_str[12..]; // Skip "irondag:"
                                    if let Ok(key_bytes) = hex::decode(hex_key) {
                                        return Some(key_bytes);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            None
        }
        Err(_) => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::rngs::OsRng;

    #[test]
    fn test_stream_type_constants() {
        assert_eq!(STREAM_TYPE_GOSSIP, 0x01);
        assert_eq!(STREAM_TYPE_SYNC, 0x02);
        assert_eq!(STREAM_TYPE_KYBER, 0x03);
    }

    #[tokio::test]
    async fn test_create_endpoint() {
        // Initialize crypto provider for rustls (required for QUIC TLS)
        init_crypto_provider();

        let signing_key = ed25519_dalek::SigningKey::generate(&mut OsRng);
        let addr: SocketAddr = "127.0.0.1:0".parse().unwrap();

        let result = create_endpoint(addr, &signing_key, 30);
        assert!(result.is_ok());

        let endpoint = result.unwrap();
        let local_addr = endpoint.local_addr().unwrap();
        assert!(local_addr.port() > 0);

        // Clean up
        endpoint.close(0u32.into(), b"test complete");
    }
}
